version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    containername: wishlist-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: wishlist-backend
    volumes:
      - mongodb_data:/data/db
    networks:
      - wishlist-network

  mongo-express:
    image: mongo-express:1.0.0
    containername: wishlist-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb
    networks:
      - wishlist-network

volumes:
  mongodb_data:

networks:
  wishlist-network:
    driver: bridge

